"use client"

import { Search, Bot, Map, Globe, FileText, Wrench } from "lucide-react"
import { Card, CardContent } from "@/components/ui/card"

const features = [
  {
    icon: Search,
    title: "SEO Audit",
    description:
      "Full technical, on-page & content analysis with 7-category scoring that covers everything from meta tags to Core Web Vitals.",
  },
  {
    icon: Bot,
    title: "GEO Analysis",
    description:
      "Generative Engine Optimization — get cited by ChatGPT, Gemini, Claude and dominate AI-powered search results.",
  },
  {
    icon: Map,
    title: "AI Roadmap",
    description:
      "Prioritized improvement plan with step-by-step tasks generated by AI to fix issues in order of impact.",
  },
  {
    icon: Globe,
    title: "Multi-Language",
    description:
      "Reports in Turkish, English, German, French and 6 more languages. Analyze websites in any language.",
  },
  {
    icon: FileText,
    title: "PDF Reports",
    description:
      "Professional, white-label ready PDF reports for your clients with your own branding and logo.",
  },
  {
    icon: Wrench,
    title: "CMS Auto-Fix",
    description:
      "AI fixes schema, meta tags, hreflang directly on your CMS. Available on the Agency plan for WordPress and more.",
  },
]

function FeatureCard({
  icon: Icon,
  title,
  description,
}: {
  icon: React.ElementType
  title: string
  description: string
}) {
  return (
    <Card className="group border-white/[0.06] bg-white/[0.02] transition-all duration-300 hover:border-emerald-500/30 hover:bg-white/[0.04]">
      <CardContent className="p-6">
        <div className="flex size-11 items-center justify-center rounded-lg bg-emerald-500/10 text-emerald-400 group-hover:bg-emerald-500/20 transition-colors">
          <Icon className="size-5" />
        </div>
        <h3 className="mt-4 text-base font-semibold">{title}</h3>
        <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
          {description}
        </p>
      </CardContent>
    </Card>
  )
}

export default function Features() {
  return (
    <section id="features" className="py-20 lg:py-28">
      <div className="mx-auto max-w-6xl px-4 lg:px-8">
        <div className="text-center">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Everything You Need to{" "}
            <span className="text-gradient">Rank Higher</span>
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-muted-foreground">
            From traditional SEO to generative AI optimization, RankFlow covers every channel where your audience discovers content.
          </p>
        </div>

        <div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((feature) => (
            <FeatureCard key={feature.title} {...feature} />
          ))}
        </div>
      </div>
    </section>
  )
}