import { ScanResult, FixSuggestion } from "@/lib/types";

type Locale = "tr" | "en" | "de";

const t = (locale: Locale) => {
  const strings: Record<string, Record<string, string>> = {
    executiveSummary: {
      tr: "Yönetici Özeti",
      en: "Executive Summary",
      de: "Zusammenfassung",
    },
    scores: { tr: "Skorlar", en: "Scores", de: "Bewertungen" },
    technicalFindings: {
      tr: "Teknik Bulgular",
      en: "Technical Findings",
      de: "Technische Ergebnisse",
    },
    onPageFindings: {
      tr: "Sayfa İçi (OnPage) Bulgular",
      en: "OnPage Findings",
      de: "OnPage Ergebnisse",
    },
    contentAnalysis: {
      tr: "İçerik Analizi",
      en: "Content Analysis",
      de: "Inhaltsanalyse",
    },
    geoAnalysis: {
      tr: "GEO (Generative Engine) Analizi",
      en: "GEO Analysis",
      de: "GEO Analyse",
    },
    roadmap: { tr: "İyileştirme Yol Haritası", en: "Roadmap", de: "Roadmap" },
    kpis: { tr: "KPI'lar", en: "KPIs", de: "KPIs" },
    url: { tr: "URL", en: "URL", de: "URL" },
    date: { tr: "Tarih", en: "Date", de: "Datum" },
    score: { tr: "Skor", en: "Score", de: "Bewertung" },
    technical: { tr: "Teknik", en: "Technical", de: "Technisch" },
    onPage: { tr: "Sayfa İçi", en: "OnPage", de: "OnPage" },
    content: { tr: "İçerik", en: "Content", de: "Inhalt" },
    geo: { tr: "GEO", en: "GEO", de: "GEO" },
    local: { tr: "Lokal", en: "Local", de: "Lokal" },
    competitor: { tr: "Rekabet", en: "Competitor", de: "Wettbewerb" },
    overall: { tr: "Genel", en: "Overall", de: "Gesamt" },
    phaseUrgent: { tr: "Faz 1: Acil (1-4 Hafta)", en: "Phase 1: Urgent (1–4 Weeks)", de: "Phase 1: Dringend (1–4 Wochen)" },
    phaseStructural: { tr: "Faz 2: Yapısal (1–3 Ay)", en: "Phase 2: Structural (1–3 Months)", de: "Phase 2: Strukturell (1–3 Monate)" },
    phaseStrategic: { tr: "Faz 3: Stratejik (3–6 Ay)", en: "Phase 3: Strategic (3–6 Months)", de: "Phase 3: Strategisch (3–6 Monate)" },
    critical: { tr: "Kritik", en: "Critical", de: "Kritisch" },
    high: { tr: "Yüksek", en: "High", de: "Hoch" },
    medium: { tr: "Orta", en: "Medium", de: "Mittel" },
    low: { tr: "Düşük", en: "Low", de: "Niedrig" },
    generatedBy: { tr: "RankFlow tarafından oluşturuldu", en: "Generated by RankFlow", de: "Erstellt von RankFlow" },
    noIssues: { tr: "Herhangi bir sorun bulunamadı.", en: "No issues found.", de: "Keine Probleme gefunden." },
    applied: { tr: "✓ Uygulandı", en: "✓ Applied", de: "✓ Angewendet" },
    notApplied: { tr: "○ Bekliyor", en: "○ Pending", de: "○ Ausstehend" },
    effort: { tr: "Efor (saat)", en: "Effort (hours)", de: "Aufwand (Std.)" },
    impact: { tr: "Etki", en: "Impact", de: "Auswirkung" },
    outOf100: { tr: "/100", en: "/100", de: "/100" },
  };

  return (key: string): string => strings[key]?.[locale] ?? strings[key]?.en ?? key;
};

function severityForPhase(severity: string): number {
  switch (severity) {
    case "critical": return 1;
    case "high": return 2;
    case "medium": return 3;
    case "low": return 3;
    default: return 2;
  }
}

function fixToRoadmapTask(fix: FixSuggestion): { phase: number; action: string; effort: number; impact: number } {
  const effortMap: Record<string, number> = {
    critical: 4,
    high: 3,
    medium: 2,
    low: 1,
  };
  const impactMap: Record<string, number> = {
    critical: 10,
    high: 7,
    medium: 4,
    low: 2,
  };
  return {
    phase: severityForPhase(fix.severity),
    action: fix.description,
    effort: effortMap[fix.severity] ?? 2,
    impact: impactMap[fix.severity] ?? 5,
  };
}

export async function generateReport(scan: ScanResult, language: string): Promise<string> {
  const locale = (["tr", "en", "de"].includes(language) ? language : "en") as Locale;
  const _ = t(locale);

  const lines: string[] = [];

  lines.push(`# RankFlow — SEO/GEO Analysis Report`);
  lines.push("");
  lines.push(`**${_("url")}:** ${scan.url}`);
  lines.push(`**${_("date")}:** ${new Date(scan.createdAt).toLocaleDateString("tr-TR")}`);
  lines.push(`**${_("generatedBy")}**`);
  lines.push("");

  // ── EXECUTIVE SUMMARY ──
  lines.push(`## ${_("executiveSummary")}`);
  lines.push("");
  const { overall } = scan.scores;
  const grade = overall >= 80 ? "A" : overall >= 60 ? "B" : overall >= 40 ? "C" : "D";
  const summaryTexts: Record<Locale, Record<string, string>> = {
    tr: {
      A: "Site performansı yüksek. Birkaç küçük iyileştirme ile mükemmel seviyeye ulaşabilir.",
      B: "Site iyi durumda ancak orta seviye iyileştirmeler ile skor artırılabilir.",
      C: "Site performansı orta seviyede. Teknik ve içerik alanlarında geliştirme gerekli.",
      D: "Site kritik sorunlar içeriyor. Acil iyileştirme gerekiyor.",
    },
    en: {
      A: "Site performance is high. A few minor improvements can bring it to excellent.",
      B: "Site is in good shape but medium-level improvements can raise the score.",
      C: "Site performance is moderate. Technical and content improvements are needed.",
      D: "Site has critical issues. Immediate improvements required.",
    },
    de: {
      A: "Die Website-Performance ist hoch. Einige kleine Verbesserungen können sie exzellent machen.",
      B: "Die Website ist in gutem Zustand, aber mittlere Verbesserungen können die Punktzahl erhöhen.",
      C: "Die Leistung ist mittelmäßig. Technische und inhaltliche Verbesserungen sind erforderlich.",
      D: "Die Website hat kritische Probleme. Sofortige Verbesserungen erforderlich.",
    },
  };
  lines.push(`**Grade: ${grade}** — ${summaryTexts[locale]?.[grade] ?? summaryTexts.en[grade]}`);
  lines.push(`**${_("overall")} ${_("score")}:** ${overall}${_("outOf100")}`);
  lines.push("");

  // ── SCORES TABLE ──
  lines.push(`## ${_("scores")}`);
  lines.push("");
  lines.push(`| ${_("technical")} | ${_("onPage")} | ${_("content")} | ${_("geo")} | ${_("local")} | ${_("competitor")} | ${_("overall")} |`);
  lines.push(`| --- | --- | --- | --- | --- | --- | --- |`);
  lines.push(
    `| ${scan.scores.technical} | ${scan.scores.onPage} | ${scan.scores.content} | ${scan.scores.geo} | ${scan.scores.local} | ${scan.scores.competitor} | **${scan.scores.overall}** |`
  );
  lines.push("");

  // ── TECHNICAL FINDINGS ──
  lines.push(`## ${_("technicalFindings")}`);
  lines.push("");
  const technicalFixes = scan.fixes.filter((f) => f.type === "technical");
  if (technicalFixes.length === 0) {
    lines.push(`> ${_("noIssues")}`);
  } else {
    for (const fix of technicalFixes) {
      const status = fix.applied ? _("applied") : _("notApplied");
      lines.push(`- **[${_(fix.severity)}]** ${fix.description} ${status}`);
      if (fix.code) lines.push(`  \`\`\`\n  ${fix.code}\n  \`\`\``);
    }
  }
  lines.push("");

  // ── ONPAGE FINDINGS ──
  lines.push(`## ${_("onPageFindings")}`);
  lines.push("");
  const onPageFixes = scan.fixes.filter((f) => f.type === "onPage");
  if (onPageFixes.length === 0) {
    lines.push(`> ${_("noIssues")}`);
  } else {
    for (const fix of onPageFixes) {
      const status = fix.applied ? _("applied") : _("notApplied");
      lines.push(`- **[${_(fix.severity)}]** ${fix.description} ${status}`);
      if (fix.code) lines.push(`  \`\`\`\n  ${fix.code}\n  \`\`\``);
    }
  }
  lines.push("");

  // ── CONTENT ANALYSIS ──
  lines.push(`## ${_("contentAnalysis")}`);
  lines.push("");
  const contentFixes = scan.fixes.filter((f) => f.type === "content");
  if (contentFixes.length === 0) {
    lines.push(`> ${_("noIssues")}`);
  } else {
    for (const fix of contentFixes) {
      const status = fix.applied ? _("applied") : _("notApplied");
      lines.push(`- **[${_(fix.severity)}]** ${fix.description} ${status}`);
    }
  }
  lines.push("");

  // ── GEO ANALYSIS ──
  lines.push(`## ${_("geoAnalysis")}`);
  lines.push("");
  const geoFixes = scan.fixes.filter((f) => f.type === "geo");
  if (geoFixes.length === 0) {
    lines.push(`> ${_("noIssues")}`);
  } else {
    for (const fix of geoFixes) {
      const status = fix.applied ? _("applied") : _("notApplied");
      lines.push(`- **[${_(fix.severity)}]** ${fix.description} ${status}`);
    }
  }
  lines.push("");

  // ── ROADMAP ──
  lines.push(`## ${_("roadmap")}`);
  lines.push("");

  const roadmapTasks = scan.fixes.map(fixToRoadmapTask);

  const phase1 = roadmapTasks.filter((t) => t.phase === 1);
  const phase2 = roadmapTasks.filter((t) => t.phase === 2);
  const phase3 = roadmapTasks.filter((t) => t.phase === 3);

  lines.push(`### ${_("phaseUrgent")}`);
  lines.push("");
  if (phase1.length === 0) {
    lines.push("> No urgent tasks at this time.");
  } else {
    lines.push(`| # | Action | ${_("effort")} | ${_("impact")} |`);
    lines.push(`| --- | --- | --- | --- |`);
    phase1.forEach((t, i) => {
      lines.push(`| ${i + 1} | ${t.action} | ${t.effort} | ${t.impact} |`);
    });
  }
  lines.push("");

  lines.push(`### ${_("phaseStructural")}`);
  lines.push("");
  if (phase2.length === 0) {
    lines.push("> No structural tasks at this time.");
  } else {
    lines.push(`| # | Action | ${_("effort")} | ${_("impact")} |`);
    lines.push(`| --- | --- | --- | --- |`);
    phase2.forEach((t, i) => {
      lines.push(`| ${i + 1} | ${t.action} | ${t.effort} | ${t.impact} |`);
    });
  }
  lines.push("");

  lines.push(`### ${_("phaseStrategic")}`);
  lines.push("");
  if (phase3.length === 0) {
    lines.push("> No strategic tasks at this time.");
  } else {
    lines.push(`| # | Action | ${_("effort")} | ${_("impact")} |`);
    lines.push(`| --- | --- | --- | --- |`);
    phase3.forEach((t, i) => {
      lines.push(`| ${i + 1} | ${t.action} | ${t.effort} | ${t.impact} |`);
    });
  }
  lines.push("");

  // ── KPIs ──
  lines.push(`## ${_("kpis")}`);
  lines.push("");
  lines.push(`| KPI | Value |`);
  lines.push(`| --- | --- |`);
  lines.push(`| ${_("overall")} ${_("score")} | ${scan.scores.overall}${_("outOf100")} |`);
  lines.push(`| ${_("technical")} ${_("score")} | ${scan.scores.technical}${_("outOf100")} |`);
  lines.push(`| ${_("onPage")} ${_("score")} | ${scan.scores.onPage}${_("outOf100")} |`);
  lines.push(`| ${_("content")} ${_("score")} | ${scan.scores.content}${_("outOf100")} |`);
  lines.push(`| ${_("geo")} ${_("score")} | ${scan.scores.geo}${_("outOf100")} |`);
  lines.push(`| ${_("critical")} issues | ${scan.fixes.filter((f) => f.severity === "critical").length} |`);
  lines.push(`| ${_("high")} issues | ${scan.fixes.filter((f) => f.severity === "high").length} |`);
  lines.push(`| ${_("medium")} issues | ${scan.fixes.filter((f) => f.severity === "medium").length} |`);
  lines.push(`| ${_("low")} issues | ${scan.fixes.filter((f) => f.severity === "low").length} |`);
  lines.push("");

  lines.push(`---`);
  lines.push(`*${_("generatedBy")}*`);

  return lines.join("\n");
}
